### PR TITLE
Add APIM logging

### PR DESCRIPTION
**Pull request by chris-pateman**
### Change description ###
Add APIM Diagnostic resource to the acceptance list

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

### CODE REVIEW

**Review by timja — COMMENTED** [review]
should a module be created for this instead?

**Comment by chris-pateman** [comment]
@timja  I can do if you think it would be worth while.
It is just a single TF resource assigned.
https://github.com/hmcts/pip-data-management/pull/103/files#diff-6909a9f409b3f5c9d65c916338c691852791655c24ef85ffc1140b9253df151f

**Review by timja — COMMENTED** [review]
Depends on if you will be using it in more than one place, if just one then probably okay, can you just add to the repo specific allow list, and not the global one ?

**Comment by chris-pateman** [comment]
@timja  yes only in one place and will only be per repo, so moved to the application specific.

**Review by timja — APPROVED** [review]

**Pull request merged**
