### PR TITLE
azure subnet

### PR DESCRIPTION
**Pull request by Don-Olu**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

request for azurerm_subnet

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
need more details before can approve this

**Comment by Don-Olu** [comment]
Previous build was using azurerm_virtual_network module with Subnets defined in-line within the Virtual Network resource, however cannot use a Virtual Network with in-line Subnets in conjunction with any Subnet resources. Doing so will cause a conflict of Subnet configurations and will overwrite subnets.

Consequently need a separate azure_rm module to define subnet resources
Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network

**Comment by timja** [comment]
Which module were you using?

Why were you doing both inline and separate?

**Review by timja — APPROVED** [review]

**Comment by Don-Olu** [comment]
using azure_rm subnet for the private endpoint so as to allow  service_endpoints    = ["Microsoft.Storage"] &   enforce_private_link_endpoint_network_policies = true definition,
This is not possible by using azurerm_virtual_network module.

**Pull request merged**
